name: Build DEB Package

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pack-deb.yml'
      - 'src/**'
      - 'deb/share/**'
      - 'deb/dpkg-conf/**'

jobs:
  build:
    name: Build DEB package
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: dpkg compile
      id: compile_deb
      working-directory: ./
      run: bash .github/scripts/compile_deb.sh

    # (Opsional) Upload artifact ke GitHub Actions
    - name: Upload DEB artifact
      uses: actions/upload-artifact@v4
      with:
        name: oneshot-deb
        path: ./*.deb
